// Generated by CoffeeScript 1.9.3
(function() {
  describe("App namespace", function() {
    return it("should be defined", function() {
      return expect(Gourmet).toBeDefined();
    });
  });

}).call(this);
